### ISSUE TITLE
"Unable to open resource"

### ISSUE THREAD

**Issue by ghost** [BuXXe/movian-cine-plugin#1]
![movian](https://cloud.githubusercontent.com/assets/17328185/14057618/c28ac9ae-f305-11e5-8587-fe637f3145d8.png)

I always get this Error. I hope you can help me :D

**Comment by BuXXe** [comment]
Yeah I noticed this one some days ago and will be working it out in the next days. I guess that the cine.to page changed their json layout and this causes the error... but thats just a guess

**Comment by ghost** [comment]
Ok, happy to hear that you already knew about this problem

BTW. Do you know why i always get the Error "No Valid Links Available" if i choose any Movie in your Kinox.to Plugin?

**Comment by BuXXe** [comment]
I just used the plugin so its not about the plugin. This mostly gives the information that either none of the links is still online or, if the hoster changed its hosting setup, my link resolution could not resolve the video file. Please try a movie which is really online and try it. If you encounter an error for a specific movie which should be online, please give me an example.

**Comment by ghost** [comment]
Yeah i tried many different movies and always the same error. For example Kung Fu Panda 3 or The 5th Wave. I can watch them on my Smartphone but with your plugin it is not working

**Comment by BuXXe** [comment]
I just tried kung fu panda with promptfile, shared and streamcloud and i always get working links. please give me a detailed example which hoster do u use? which platform? Movian version?

**Comment by BuXXe** [comment]
fixed the error in cine.to. just wait for the official release in the plugin section of movian or download it from the github

**Comment by ghost** [comment]
Solved

I forgot that I installed an Bleeding Edge Version... After installing an Stable Version the problem solved

Thank you anyway

**Comment by ghost** [comment]
Thanks for fixing, you are the best (Y)

**Comment by BuXXe** [comment]
No problem. thanks for the bug report.

**Comment by ghost** [comment]
Just tried it and got the same error but this time if i choose a movie

![movian_1](https://cloud.githubusercontent.com/assets/17328185/14058256/140d7e92-f31b-11e5-91c8-2f3d641209f4.png)

**Comment by BuXXe** [comment]
-.- im an idiot. give me a minute

**Comment by BuXXe** [comment]
Ok it seems that besides the problem with the new redirection, cine.to changed their way of protecting outgoing links. I found the error but no fix yet. working on it.

**Comment by ghost** [comment]
Thank you

**Comment by BuXXe** [comment]
So, had a hard time working that thing out. I came across another problem related to flashx and the redirection to a second server while debugging this one. It seems that there also was something wrong with streamcloud / cine.to's redirection for streamcloud links on that day because right now, the problem seems to be gone. Still, the main issue of "unable to open resource" was my fault and should be fixed now. just wait for release or use the release from github. 

Thank you for your feedback.
