### ISSUE TITLE
invalid json (at offset 1)

### ISSUE THREAD

**Issue by angomania** [BuXXe/movian-cine-plugin#3]
Error since yesterday:

cine.to::MovieLanguageSelection:xxxxxxx   <--- Depending on film the number changes
invalid json (at offset 1)

**Comment by BuXXe** [comment]
Do you already use the v0.2 which was released some days ago?

**Comment by angomania** [comment]
Yes, I´ve replaced the plugin with your 0.2 update. 
It was working for 2 days. Since yesterday I get the error.

**Comment by BuXXe** [comment]
I just tried it with the up to date version in the official movian plugins browser and i dont get any errors. I also opened various movies and still no problems. Which movian Version do you use? Did you do an update to Movian 5.0? I dont use 5.0 so i cannot say anything about plugin compatibility with this Version.
If the Problem persists, please give me some info about platform, Versions, specific movies the error occurs with and perhaps the error log

**Comment by angomania** [comment]
Ok,it´s working now after reinstalling the plugin from the reposity today.

I´ve installed your update 5 days ago from my pc to the ps3, because it wasn´t in the reposity.
It was working fine for a few days. No idea whats going wrong. 

Btw I´ve tested movian 5.0 but I don´t like the new interface and revert back to the latest v4 version.

**Comment by BuXXe** [comment]
Fine. Same for me. I tested the beta of 5.0 and the UI was one of the main reasons for me to stick with v4. Furthermore, some of the features existing for some time in showtime and movian are still missing / were removed. So as long as I cant find a big improvement, i will not set sail and move over :)
