### ISSUE TITLE
Unable To Open Resource (Invalid Json at Offset 1)

### ISSUE THREAD

**Issue by TwiistOnYT** [BuXXe/movian-cine-plugin#4]
I cant open any apps up on Movian, i keep getting the error "Unable To Open Resource".
IDK What to do, help me fix this ASAP. Thanks.

**Comment by TwiistOnYT** [comment]
(https://user-images.githubusercontent.com/34987428/34463409-233b3b2c-ee53-11e7-991c-5ffc7728a4af.JPG) This is what it shows me on Cine.to

**Comment by BuXXe** [comment]
I looked at the plugin currently available and cannot recreate the error. It is not connected to a plugin so perhaps check ur Network Setup. Furthermore, a correct ssl connection needs correct time setup so check if the system has correct time settings. will close here cause it is not connected to the plugin.
